
// [root.txt.inc] Copyright (c) 2000 IBM, Inc. and Others, all rights reserved
   c.gif:import { "root/c.gif" }
   opened.gif:import { "root/opened.gif" }
   closed.gif:import { "root/closed.gif" }
   help.html:import  { "root/help.html" }
	transliteration.html:import { "root/transliteration.html" }
   displayproblems.gif:import { "root/displayproblems.gif" }
   explore.gif:import { "root/explore.gif" }
   help.gif:import { "root/help.gif" }
   incorrect.gif:import { "root/incorrect.gif" }
   lx.jpg:import { "root/lx.jpg" }
   lxbar_dev.jpg:import { "root/lxbar_dev.jpg" }
   lxbar_g.gif:import { "root/lxbar_g.gif" }
   lxbar_ibm.jpg:import { "root/lxbar_ibm.jpg" }
   lxbar_icu.jpg:import { "root/lxbar_icu.jpg" }

// tab
   tab_bot.gif:import { "root/tab_bot.gif" }
   tab_aleft.gif:import { "root/tab_aleft.gif" }
   tab_aright.gif:import { "root/tab_aright.gif" }

