#!/bin/sh

SRCFILES='convrtrs.txt index.txt default.txt translit/index.txt'

if [ ! -f $1/convrtrs.txt ]; then
        echo Usage: $0 path/to/icu/data/
        echo
        echo   
        echo Use the path to the ORIGINAL icu/data directory, where the ICU was built.
        echo 
        exit 1
fi


ODIR=`pwd`


cd $1

for file in  $SRCFILES ; do
        if [ ! -f $file ]; then
          echo ERR: $1/$file does not exist!
          exit 1
        else
         rm -f $ODIR/$file.orig 2> /dev/null
         cp $1/$file $ODIR/$file.orig
         echo  $ODIR/$file.orig
        fi
done

cd $ODIR

DS='$*'

cat > rebuildData.sh <<EOF
#!/bin/sh
cp $DS $1/
echo copying $DS $1/
if [ ! -f $1/../source/tools/makeconv/ucmlocal.mk ]; then
    cp ucmlocal.mk $1/../source/tools/makeconv/ucmlocal.mk
fi
cd $1/../source/tools
cd makeconv
make 
cd ..
make -f Makefile build-local install-local
if [ -f $1/../source/tools/makeconv/ucmlocal.mk ]; then
    echo NOT over-writing $1/../source/tools/makeconv/ucmlocal.mk - move out of the way manually!
fi
EOF

chmod u+x rebuildData.sh
