#!/bin/sh
## ******************************************************************************
## *
## *   Copyright (C) 1999-2005, International Business Machines
## *   Corporation and others.  All Rights Reserved.
## *
## *******************************************************************************

echo "// Generated by genIndex.sh " `date` "@" `hostname`
echo "res_index {"
echo "    InstalledLocales {"
# Following line generates index of ALL .txt files
#    cat *.txt | grep "^[a-z]" | sed "s/\([a-zA-Z_]*\).*/         \1,/" | sort
    for BUND in `echo $* | sed -e 's/.txt//g'`; do
        echo "        \"$BUND\" { \"\" }" | fgrep -v root
    done
echo "    }"
echo "}"

    
