#!/bin/sh
## ******************************************************************************
## *
## *   Copyright (C) 1999-2000, International Business Machines
## *   Corporation and others.  All Rights Reserved.
## *
## *******************************************************************************

echo "# Generated by genIndex.sh " `date` "@" `hostname`
echo "index"
echo "{"
echo "    InstalledLocales"
echo "    {"
# Following line generates index of ALL .txt files
#    cat *.txt | grep "^[a-z]" | sed "s/\([a-zA-Z_]*\).*/         \1,/" | sort
    cat $@ | grep "^[a-z]" | sed "s/\([a-zA-Z_]*\).*/         \1,/" | sort
echo "    }"
echo "}"

    
