name: Push to GCR Github Action
on:
  push:
    tags:
    - '*'
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build icu4jweb with Maven
      run: >
        mvn --file icu4jweb/pom.xml -s .github/workflows/mvn-settings.xml -B package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the tag name
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
    - name: Build and Upload ICU4C-Demos Container
      uses: RafikFarhad/push-to-gcr-github-action@v3
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: us.gcr.io
        project_id: icu4c-demos
        image_name: icu4c-demos
        image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
        dockerfile: icu-kube/docker.d/icu4c-demos/Dockerfile
        context: .
        build_args: ICU_PATH=system
    - name: Build and Upload ICU4J-Demos Container
      uses: RafikFarhad/push-to-gcr-github-action@v3
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: us.gcr.io
        project_id: icu4c-demos
        image_name: icu4j-demos
        image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
        dockerfile: icu4jweb/Dockerfile
        context: icu4jweb
